import type { Metadata } from "next";
import "./global.css"; // Ensures Tailwind works

export const metadata: Metadata = {
  title: "Cires Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-gray-50">
        {/* 'children' is where your page.tsx content will be injected */}
        {children}
      </body>
    </html>
  );
}